version: "3.9"
services:
  pi-emulator:
    # We use ptrsr/pi-ci in the future this may change to a custom image to support other raspberry pi OS's eg. Diet Pi
    image: ptrsr/pi-ci
    command: start
    volumes:
      - ./dist:/dist
    networks:
      connector:
        ipv4_address: 172.16.238.10
    ports:
      - 2222:2222

  ansible-playbook:
    command: -i inventory main.yml
    image: andrerc1/ansible
    depends_on:
      - pi-emulator
    volumes:
      - ./ansible/playbooks:/ansible/playbooks
      - ./files:/files
      - ./dist:/distro
    networks:
      connector:
        ipv4_address: 172.16.238.11

volumes:
  dist:
  playbook:
  files:

networks:
  connector:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
